import { Injectable, InternalServerErrorException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { GetObjectCommand, PutObjectCommand, S3Client } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { randomUUID } from 'crypto';
import * as path from 'path';
import type { DownloadTarget, StorageProvider } from './storage.provider';

/**
 * Website Launch (Step 4): Cloudflare R2 storage provider. R2 speaks the
 * S3 API, so this uses the standard AWS SDK v3 S3Client pointed at R2's
 * account-specific endpoint rather than a Cloudflare-specific SDK — the
 * only R2-specific things here are the endpoint URL and `region: 'auto'`
 * (R2's documented convention; the value is otherwise ignored by R2).
 *
 * Bucket contents are private — every object is written with no public
 * ACL, and the only way to read one back is a short-lived presigned URL
 * generated by getDownloadTarget(), exactly mirroring
 * LocalStorageProvider's own access-control posture (DocumentsService has
 * already confirmed the caller may see this specific document before
 * either provider is ever called). The browser downloads directly from
 * R2 on that presigned URL — file bytes never flow back through this API.
 *
 * StorageModule always constructs one instance of every provider (Nest
 * resolves whatever the factory function injects, eagerly, before it can
 * even check STORAGE_DRIVER) — so this provider is instantiated in every
 * environment, including local dev with no R2 credentials configured.
 * Reading R2_* env vars is therefore deliberately deferred to first use
 * (`client` getter), not done in the constructor, so an environment that
 * never actually calls save()/getDownloadTarget() on this provider (i.e.
 * STORAGE_DRIVER=local) is completely unaffected by missing R2 config.
 */
@Injectable()
export class R2StorageProvider implements StorageProvider {
  private cachedClient: S3Client | undefined;
  private cachedBucket: string | undefined;

  constructor(private readonly config: ConfigService) {}

  async save(params: { tenantId: string; fileName: string; buffer: Buffer }): Promise<string> {
    const safeName = sanitizeFileName(params.fileName);
    const storageKey = `${params.tenantId}/${randomUUID()}-${safeName}`;

    await this.client.send(
      new PutObjectCommand({
        Bucket: this.bucket,
        Key: storageKey,
        Body: params.buffer,
      }),
    );

    return storageKey;
  }

  async getDownloadTarget(storageKey: string): Promise<DownloadTarget> {
    const url = await getSignedUrl(
      this.client,
      new GetObjectCommand({ Bucket: this.bucket, Key: storageKey }),
      { expiresIn: 300 }, // 5 minutes — long enough for a browser to start the download, short enough to limit exposure if the URL leaks
    );
    return { kind: 'redirect', url };
  }

  private get bucket(): string {
    this.cachedBucket ??= requireEnv(this.config, 'R2_BUCKET_NAME');
    return this.cachedBucket;
  }

  private get client(): S3Client {
    if (!this.cachedClient) {
      const accountId = requireEnv(this.config, 'R2_ACCOUNT_ID');
      const accessKeyId = requireEnv(this.config, 'R2_ACCESS_KEY_ID');
      const secretAccessKey = requireEnv(this.config, 'R2_SECRET_ACCESS_KEY');
      this.cachedClient = new S3Client({
        region: 'auto',
        endpoint: `https://${accountId}.r2.cloudflarestorage.com`,
        credentials: { accessKeyId, secretAccessKey },
      });
    }
    return this.cachedClient;
  }
}

function requireEnv(config: ConfigService, key: string): string {
  const value = config.get<string>(key);
  if (!value) {
    throw new InternalServerErrorException(`Missing required env var "${key}" for STORAGE_DRIVER=r2`);
  }
  return value;
}

/** Mirrors LocalStorageProvider's own sanitizer — see its doc comment. */
function sanitizeFileName(original: string): string {
  const base = path.basename(original).replace(/[^a-zA-Z0-9.\-_ ]/g, '_');
  return base.slice(0, 150) || 'file';
}
